### ISSUE TITLE
Error: Couldn't find inherited node "OptionsListButtonTemplate"

### ISSUE THREAD

**Issue by Marty** [miraage/gladdy#4]
Hi,

I was just looking for a nice arena addon for tbc and luckily found this repo.
The addon seems to work fine, but in the options menu when I click the "Gladdy" node, I get the following error and the left menu area stays empty. I'm guessing there should be more options, am I right?

![gladdy_bug](https://cloud.githubusercontent.com/assets/100658/9712842/df0ab34c-554d-11e5-9fdb-a51b0ab75803.png)

```
Error: CreateFrame(): Couldn't find inherited node "OptionsListButtonTemplate"
File:...s\Ace3\AceGUI-3.0\widgets\AceGUIWidget-TreeGroup.lua
Line:146
```

Maybe someone still looks into this repo :)
Greetings

**Comment by Schaka** [comment]
This addon hasn't been in development for years. Either way, your probem seems to be with a broken version of Ace3. Get rid of any other addon that employs Ace3 or delete it from that folder.

I have done my own fixes to Gladdy, but not all of them are worth pushing because some cater specifically to a range of private servers - download here:
http://www.mediafire.com/download/4wegjc2zn0ovnw0/gladdy.zip

**Comment by Marty** [comment]
Thank you sir, that was very helpful. Range Display was interfering in my case.
Why don't you create a fork with your fixes? (:

**Comment by Schaka** [comment]
I do have that fork. But it doesn't contain all fixes and some are just hacky. So there is no point in pushing any more to it than I currently have. 
No point pushing half-finished or hacky code.

**Comment by Marty** [comment]
+1 - didn't see that fork.
